/**@author Diana
 * Klasse erstellt und erweitert von Diana
 *
 * Fenster zum Einlesen der Namen und Gesamtpunktzahl der Aufgaben in der Dozentenansicht
 */

package GUI;

import Klassen.Student;
import Klassen.Veranstaltung;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

public class DAufgabenInformationen implements FrameContent {
    GUIMain mainFrame;
    private JPanel DAufgabenInformationenPanel;
    private JLabel aufgabenNameLabel;
    private JTextField aufgabenNameTextField;
    private JLabel seitenanzahlLabel;
    private JButton weiterButton;
    private JTextField gesamtPunktzahlTextField;

    public String getName() {
        return "Aufgabeninformationen hinzufügen - Dozent";
    }

    public JPanel getPanel() {
        return DAufgabenInformationenPanel;
    }

    public void setParentFrame(GUIMain m) {
        mainFrame = m;
    }

    public DAufgabenInformationen(ArrayList<Veranstaltung> dVL, int aufAnzahl, String leistung, String ub, int index, int counter) {
        seitenanzahlLabel.setText(counter + " / " + aufAnzahl);

        if (aufAnzahl == counter) {
            weiterButton.setText("OK");
        }

        weiterButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    mainFrame.getController().createAufgabe(dVL.get(index), leistung, ub, aufgabenNameTextField.getText(), Integer.parseInt(gesamtPunktzahlTextField.getText()));
                    if (aufAnzahl == counter) {
                        mainFrame.setContent(new DLeistungUebersichtbearbeiten(dVL, index));
                    } else {
                        mainFrame.setContent(new DAufgabenInformationen(dVL, aufAnzahl, leistung, ub, index, counter + 1));
                    }
                } catch (Exception ex) {
                    ErrorDialog eD = new ErrorDialog("ups, something went wrong");
                    eD.setResizable(false);
                    eD.setLocationRelativeTo(null);
                    eD.setVisible(true);
                    return;
                }

            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        DAufgabenInformationenPanel = new JPanel();
        DAufgabenInformationenPanel.setLayout(new GridLayoutManager(3, 2, new Insets(250, 200, 250, 250), -1, -1));
        aufgabenNameLabel = new JLabel();
        aufgabenNameLabel.setText("Aufgabenname:");
        DAufgabenInformationenPanel.add(aufgabenNameLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        aufgabenNameTextField = new JTextField();
        DAufgabenInformationenPanel.add(aufgabenNameTextField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(80, -1), new Dimension(80, -1), new Dimension(80, -1), 0, false));
        seitenanzahlLabel = new JLabel();
        seitenanzahlLabel.setText("Seitenanzahl");
        DAufgabenInformationenPanel.add(seitenanzahlLabel, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        weiterButton = new JButton();
        weiterButton.setText("weiter");
        DAufgabenInformationenPanel.add(weiterButton, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Gesamtpunktzahl");
        DAufgabenInformationenPanel.add(label1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        gesamtPunktzahlTextField = new JTextField();
        DAufgabenInformationenPanel.add(gesamtPunktzahlTextField, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(80, -1), new Dimension(80, -1), new Dimension(80, -1), 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return DAufgabenInformationenPanel;
    }

}
