/**@author Kristi, Diana
 * Klasse erstellt von Kristi und erweitert von Diana
 *
 * Fenster in dem der Dozent eine Übersicht über die Leistungen hat
 * */

package GUI;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import Klassen.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.ArrayList;

public class DLeistungsuebersicht implements FrameContent {

    /**
     * @author Kristi
     */
    private GUIMain mainFrame;
    private JLabel BewertungLabel;
    private JButton leistungHinzufuegen;
    private JButton UBhinzufuegen;
    private JButton loeschen;
    private JTextField Bewertung;
    private JPanel LeistungsuebersichtPanel;
    private JButton zurueckButton;
    private JButton teambewertungButton;
    private JButton hinzufuegen;
    private JScrollPane treeScrollPane;
    private JTree tree;
    /**
     * @author Diana
     */
    private JButton logoutButton;
    private JButton aufgabeHinzufuegen;

    /**
     * @author Kristi
     */
    public String getName() {

        return "Leistungsübersicht - Dozent";
    }

    public JPanel getPanel() {

        return LeistungsuebersichtPanel;
    }

    public void setParentFrame(GUIMain m) {

        mainFrame = m;
    }

    /**
     * @param dVL
     * @param student
     * @param index
     * @author Diana
     */
    public DLeistungsuebersicht(ArrayList<Veranstaltung> dVL, Student student, int index) {

        //Initialisierung Baum mit Gruppen, Teams und Mitglieder
        treeScrollPane.setViewportView(tree);

        //Überpruefung des ScrollPane auf Veraenderungen und Aktualisierung der Daten mit Hilfe der Datenbank
        treeScrollPane.addPropertyChangeListener(new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                tree = mainFrame.getController().createLeistungsTree(dVL.get(index), student, treeScrollPane);
            }
        });

        //zum Hinzufuegen eines Leistungsblocks als Parent in den Tree
        leistungHinzufuegen.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                //To Do: neuen LB in Tree und DB hinzufügen

                mainFrame.setContent(new DLeistungsuebersicht(dVL, student, index));
            }
        });
        //zum Hinzufuegen eines Unterblocks als Child in den Tree
        UBhinzufuegen.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                //To Do: neuen UB in Tree und DB hinzufügen

                mainFrame.setContent(new DLeistungsuebersicht(dVL, student, index));
            }
        });
        //zum Hinzufuegen einer Aufgabe (z.b. Aufgabe 1 von Hausaufgabe 1)
        aufgabeHinzufuegen.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });
        //zum Hinzufuegen von Einzelleistungen für einen Studenten
        hinzufuegen.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                //To Do: Einzelleistung aus obigem Textfeld einem Studenten zuordnen + in DB speichern

            }
        });
        //zum Hinzufuegen von Gruppenleistungen für ein Team
        teambewertungButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                //To Do: Teamleistung aus obigem Textfeld einem Team zuordnen + in DB speichern
            }
        });
        //zum Loeschen des ausgewaehlten Leistungs- oder Unterblocks
        loeschen.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                mainFrame.setContent(new DLeistungsuebersicht(dVL, student, index));
            }
        });
        //Wechsel zurück zum Fenster Gruppenübersicht in der Dozentenansicht
        zurueckButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                mainFrame.setContent(new DGruppenuebersicht(dVL, index));
            }
        });
        //Logout
        logoutButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                mainFrame.setContent(new LogoutSeite());
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        LeistungsuebersichtPanel = new JPanel();
        LeistungsuebersichtPanel.setLayout(new GridLayoutManager(10, 4, new Insets(50, 20, 50, 20), -1, -1));
        hinzufuegen = new JButton();
        hinzufuegen.setText("Einzelbewertung hinzufügen");
        LeistungsuebersichtPanel.add(hinzufuegen, new GridConstraints(5, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        loeschen = new JButton();
        loeschen.setText("Element löschen");
        LeistungsuebersichtPanel.add(loeschen, new GridConstraints(7, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        BewertungLabel = new JLabel();
        BewertungLabel.setText("Bewertung");
        LeistungsuebersichtPanel.add(BewertungLabel, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        zurueckButton = new JButton();
        zurueckButton.setText("zurück");
        LeistungsuebersichtPanel.add(zurueckButton, new GridConstraints(9, 1, 1, 2, GridConstraints.ANCHOR_SOUTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        teambewertungButton = new JButton();
        teambewertungButton.setText("Teambewertung hinzufügen");
        LeistungsuebersichtPanel.add(teambewertungButton, new GridConstraints(6, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        Bewertung = new JTextField();
        Bewertung.setText("");
        LeistungsuebersichtPanel.add(Bewertung, new GridConstraints(4, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(50, -1), new Dimension(50, -1), new Dimension(50, -1), 0, false));
        final Spacer spacer1 = new Spacer();
        LeistungsuebersichtPanel.add(spacer1, new GridConstraints(8, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        treeScrollPane = new JScrollPane();
        LeistungsuebersichtPanel.add(treeScrollPane, new GridConstraints(0, 0, 10, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        tree = new JTree();
        treeScrollPane.setViewportView(tree);
        leistungHinzufuegen = new JButton();
        leistungHinzufuegen.setText("Leistung hinzufügen");
        LeistungsuebersichtPanel.add(leistungHinzufuegen, new GridConstraints(0, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        UBhinzufuegen = new JButton();
        UBhinzufuegen.setText("Unterblock hinzufügen");
        LeistungsuebersichtPanel.add(UBhinzufuegen, new GridConstraints(1, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        logoutButton = new JButton();
        logoutButton.setText("Logout");
        LeistungsuebersichtPanel.add(logoutButton, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        aufgabeHinzufuegen = new JButton();
        aufgabeHinzufuegen.setText("Aufgabe hinzufügen");
        LeistungsuebersichtPanel.add(aufgabeHinzufuegen, new GridConstraints(2, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        LeistungsuebersichtPanel.add(spacer2, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return LeistungsuebersichtPanel;
    }

}
