/**@author Diana
 * Klasse erstellt und erweitert von Diana
 *
 * Fenster zum Einlesen der Namen der Leistungen in der Dozentenansicht
 */

package GUI;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import Klassen.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

public class DLeistungsInformationen implements FrameContent {
    GUIMain mainFrame;
    private JPanel DLeistungsInformationenPanel;
    private JLabel leistungsnameLabel;
    private JTextField leistungsnameTextField;
    private JButton weiterButton;
    private JLabel seitenanzahlLabel;

    public String getName() {
        return "Leistungsinformationen hinzufügen - Dozent";
    }

    public JPanel getPanel() {
        return DLeistungsInformationenPanel;
    }

    public void setParentFrame(GUIMain m) {
        mainFrame = m;
    }

    public DLeistungsInformationen(ArrayList<Veranstaltung> dVL, Student student, int leistAnzahl, int index, int counter) {

        seitenanzahlLabel.setText(counter + " / " + leistAnzahl);

        if (leistAnzahl == counter) {
            weiterButton.setText("OK");
        }

        weiterButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    mainFrame.getController().createLeistung(dVL.get(index), leistungsnameTextField.getText());
                    if (leistAnzahl == counter) {
                        mainFrame.setContent(new DLeistungsuebersicht(dVL, student, index));
                    } else {
                        mainFrame.setContent(new DLeistungsInformationen(dVL, student, leistAnzahl, index, counter + 1));
                    }
                } catch (Exception ex) {
                    ErrorDialog eD = new ErrorDialog("ups, something went wrong");
                    eD.setResizable(false);
                    eD.setLocationRelativeTo(null);
                    eD.setVisible(true);
                    return;
                }

            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        DLeistungsInformationenPanel = new JPanel();
        DLeistungsInformationenPanel.setLayout(new GridLayoutManager(2, 2, new Insets(250, 200, 250, 300), -1, -1));
        leistungsnameLabel = new JLabel();
        leistungsnameLabel.setText("Leistungsname:");
        DLeistungsInformationenPanel.add(leistungsnameLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        weiterButton = new JButton();
        weiterButton.setText("weiter");
        DLeistungsInformationenPanel.add(weiterButton, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        leistungsnameTextField = new JTextField();
        DLeistungsInformationenPanel.add(leistungsnameTextField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        seitenanzahlLabel = new JLabel();
        seitenanzahlLabel.setText("Label");
        DLeistungsInformationenPanel.add(seitenanzahlLabel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return DLeistungsInformationenPanel;
    }
}
