/**@author Diana
 * Klasse erstellt und erweitert von Diana
 *
 * Fenster zum Einlesen der Namen der Unterbloecke in der Dozentenansicht
 */

package GUI;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import Klassen.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

public class DUbInformationen implements FrameContent {
    GUIMain mainFrame;
    private JPanel DUbInformationenPanel;
    private JLabel ubNameLabel;
    private JTextField ubNameTextField;
    private JLabel seitenanzahlLabel;
    private JButton weiterButton;

    public String getName() {
        return "Unterblockinformationen hinzufügen - Dozent";
    }

    public JPanel getPanel() {
        return DUbInformationenPanel;
    }

    public void setParentFrame(GUIMain m) {
        mainFrame = m;
    }

    public DUbInformationen(ArrayList<Veranstaltung> dVL, Student student, int unterblockAnzahl, String leistung, int index, int counter) {

        seitenanzahlLabel.setText(counter + " / " + unterblockAnzahl);

        if (unterblockAnzahl == counter) {
            weiterButton.setText("OK");
        }

        weiterButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    mainFrame.getController().createUnterblock(dVL.get(index), leistung, ubNameTextField.getText());
                    if (unterblockAnzahl == counter) {
                        mainFrame.setContent(new DLeistungsuebersicht(dVL, student, index));
                    } else {
                        mainFrame.setContent(new DUbInformationen(dVL, student, unterblockAnzahl, leistung, index, counter + 1));
                    }
                } catch (Exception ex) {
                    ErrorDialog eD = new ErrorDialog("ups, something went wrong");
                    eD.setResizable(false);
                    eD.setLocationRelativeTo(null);
                    eD.setVisible(true);
                    return;
                }

            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        DUbInformationenPanel = new JPanel();
        DUbInformationenPanel.setLayout(new GridLayoutManager(2, 2, new Insets(250, 200, 250, 300), -1, -1));
        ubNameLabel = new JLabel();
        ubNameLabel.setText("Unterblockname");
        DUbInformationenPanel.add(ubNameLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ubNameTextField = new JTextField();
        DUbInformationenPanel.add(ubNameTextField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(80, -1), new Dimension(80, -1), new Dimension(80, -1), 0, false));
        seitenanzahlLabel = new JLabel();
        seitenanzahlLabel.setText("Label");
        DUbInformationenPanel.add(seitenanzahlLabel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        weiterButton = new JButton();
        weiterButton.setText("weiter");
        DUbInformationenPanel.add(weiterButton, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return DUbInformationenPanel;
    }

}