/**@author Kristi, Diana
 * Klasse erstellt von Kristi und erweitert von Diana
 *
 * Fenster in dem der Dozent die Informationen der Veranstaltung einsehen kann
 * */

package GUI;

import Klassen.Veranstaltung;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

public class DVeranstaltungsuebersicht implements FrameContent {

    /**@author Kristi*/
    private GUIMain mainFrame;

    private JPanel VeranstaltungsuebersichtPanel;
    //JList wird erstellt
    private JList VeranstalungenList;
    private DefaultListModel dLV = new DefaultListModel();
    private JScrollPane scrollPane;
    private JButton einsehen;
    /**@author Diana*/
    private JButton logoutButton;
    private JLabel errorLabel;

    /**@author Kristi*/
    public String getName() {

        return "Veranstaltungsübersicht - Dozent";
    }

    public JPanel getPanel() {

        return VeranstaltungsuebersichtPanel;
    }

    public void setParentFrame(GUIMain m) {

        mainFrame = m;
    }

    /**@author Diana*/
    public DVeranstaltungsuebersicht(ArrayList<Veranstaltung> dVL, int index) {

        ArrayList<String> veranstaltungen = new ArrayList<String>();

        for (Veranstaltung v : dVL) {
            veranstaltungen.add(v.getName());
        }

        dLV.addAll(veranstaltungen);
        VeranstalungenList.setModel(dLV);

        einsehen.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                if (VeranstalungenList.getSelectedIndex() >= 0) {
                    mainFrame.setContent(new DVeranstaltung(dVL, VeranstalungenList.getSelectedIndex()));
                } else {
                    errorLabel.setVisible(true);
                }

            }
        });
        logoutButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                mainFrame.setContent(new LogoutSeite());
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        VeranstaltungsuebersichtPanel = new JPanel();
        VeranstaltungsuebersichtPanel.setLayout(new GridLayoutManager(3, 3, new Insets(50, 20, 50, 20), -1, -1));
        einsehen = new JButton();
        einsehen.setText("Veranstaltung einsehen");
        VeranstaltungsuebersichtPanel.add(einsehen, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        logoutButton = new JButton();
        logoutButton.setText("Logout");
        VeranstaltungsuebersichtPanel.add(logoutButton, new GridConstraints(0, 2, 3, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        scrollPane = new JScrollPane();
        VeranstaltungsuebersichtPanel.add(scrollPane, new GridConstraints(0, 0, 3, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        VeranstalungenList = new JList();
        scrollPane.setViewportView(VeranstalungenList);
        errorLabel = new JLabel();
        errorLabel.setFocusable(false);
        errorLabel.setForeground(new Color(-52480));
        errorLabel.setText("Keine Veranstaltung ausgewählt!");
        errorLabel.setVisible(false);
        VeranstaltungsuebersichtPanel.add(errorLabel, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        VeranstaltungsuebersichtPanel.add(spacer1, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return VeranstaltungsuebersichtPanel;
    }
}
