/**@author Kristi, Diana
 * Klasse erstellt von Kristi und erweitert von Diana
 *
 * Fenster in dem der Dozent eine Übersicht über die ihm zugehörige Veranstaltungen hat
 * */
package GUI;

import Klassen.Dozent;
import Klassen.Veranstaltung;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

public class DVeranstaltung implements FrameContent {

    /**@author Kristi*/
    private GUIMain mainFrame;
    public JPanel VeranstaltungPanel;
    private JButton InfosBearbeiten;
    private JButton GrTeEinsehen;
    private JButton zurueck;
    private JTextPane infos;
    private JTextPane dozent;
    private JLabel infosField;
    private JLabel dozentField;
    private JButton logoutButton;

    public String getName() { return "Veranstaltung - Dozent"; }

    public JPanel getPanel() { return VeranstaltungPanel; }

    public void setParentFrame(GUIMain m) { mainFrame = m; }

    /**@author Diana*/
    public DVeranstaltung(ArrayList<Veranstaltung> dVL, int index) {

        String d = "";

        ArrayList<Dozent> dozenten = dVL.get(index).getDozenten();
        for (Dozent doz : dozenten) {
            d += doz.getTitel() + " " + doz.getVorname() + " " + doz.getNachname() + "\n";
        }

        infos.setText(dVL.get(index).getBeschreibung());
        dozent.setText(d);

        InfosBearbeiten.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                mainFrame.setContent(new DVeranstaltungbearbeiten(dVL, index));
            }
        });
        GrTeEinsehen.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                mainFrame.setContent(new DGruppenuebersicht(dVL, index));
            }
        });
        zurueck.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                mainFrame.setContent(new DVeranstaltungsuebersicht(dVL, index));
            }
        });
        logoutButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                mainFrame.setContent(new LogoutSeite());
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        VeranstaltungPanel = new JPanel();
        VeranstaltungPanel.setLayout(new GridLayoutManager(5, 3, new Insets(50, 20, 50, 20), -1, -1));
        infos = new JTextPane();
        infos.setEditable(false);
        VeranstaltungPanel.add(infos, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        dozent = new JTextPane();
        dozent.setEditable(false);
        VeranstaltungPanel.add(dozent, new GridConstraints(3, 0, 2, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        infosField = new JLabel();
        infosField.setText("Veranstaltungsinformationen");
        VeranstaltungPanel.add(infosField, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        zurueck = new JButton();
        zurueck.setText("zurück");
        VeranstaltungPanel.add(zurueck, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_SOUTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        logoutButton = new JButton();
        logoutButton.setText("Logout");
        VeranstaltungPanel.add(logoutButton, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        VeranstaltungPanel.add(spacer1, new GridConstraints(2, 1, 2, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        dozentField = new JLabel();
        dozentField.setText("Dozent(en)");
        VeranstaltungPanel.add(dozentField, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        InfosBearbeiten = new JButton();
        InfosBearbeiten.setText("Informationen bearbeiten");
        VeranstaltungPanel.add(InfosBearbeiten, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        GrTeEinsehen = new JButton();
        GrTeEinsehen.setText("Gruppen und Teams einsehen");
        VeranstaltungPanel.add(GrTeEinsehen, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return VeranstaltungPanel;
    }

}
