package GUI;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class LoginSeite implements FrameContent {

    private GUIMain mainFrame;

    private JPanel LoginPanel;
    //Eingabe der E-Mailadresse (vorname.name)
    private JTextField emailField;
    private JPasswordField passwordField;
    private JButton loginButton;
    private JButton registrierenButton;
    private JLabel passwortLabel;
    private JLabel eMailadresseLabel;
    private JLabel uniRostockDeLabel;
    private JLabel errorLabel;


    public String getName() {

        return "Login";
    }

    public JPanel getPanel() {

        return LoginPanel;
    }

    public void setParentFrame(GUIMain m) {

        mainFrame = m;
    }

    public LoginSeite() {


        registrierenButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                mainFrame.setContent(new RegistrierenSeite());
            }
        });
        loginButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                //TODO: Fehlermeldung, wenn E-Mailfeld leer
                try {
                    emailField.getText().isEmpty();
                } catch (Exception ex) {

                    errorLabel.setVisible(true);
                    errorLabel.setText("leere Eingabe im E-Mailfeld");
                    ex.printStackTrace();
                    System.out.println(ex);
                    return;
                }
                //TODO: Fehlermeldung bei falscher Eingabe des Passwortes


                //gets the controller reference from the GUIMain object
                //then calls the login method with the data in the data from the email and password text fields
                mainFrame.getController().login(emailField.getText() + "@uni-rostock.de", passwordField.getPassword());
            }
        });

        //TODO: Exception bei Eingabe von @
        /*emailField.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                super.keyPressed(e);
                try {
                    String str = emailField.getText();
                }
                catch (){

                    errorLabel.setVisible(true);
                    errorLabel.setText("Eingabe ohne @uni-rostock.de");
            }
        });*/
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        LoginPanel = new JPanel();
        LoginPanel.setLayout(new GridLayoutManager(3, 3, new Insets(50, 50, 450, 300), -1, -1));
        passwortLabel = new JLabel();
        passwortLabel.setText("Passwort");
        passwortLabel.setVerticalAlignment(1);
        passwortLabel.setVerticalTextPosition(1);
        LoginPanel.add(passwortLabel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        eMailadresseLabel = new JLabel();
        eMailadresseLabel.setText("E-Mailadresse");
        eMailadresseLabel.setVerticalAlignment(1);
        eMailadresseLabel.setVerticalTextPosition(1);
        LoginPanel.add(eMailadresseLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        registrierenButton = new JButton();
        registrierenButton.setMargin(new Insets(0, 0, 0, 0));
        registrierenButton.setText("Registrieren");
        registrierenButton.setVerticalAlignment(0);
        registrierenButton.setVerticalTextPosition(0);
        LoginPanel.add(registrierenButton, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, new Dimension(150, 20), new Dimension(150, 20), new Dimension(150, 20), 0, false));
        loginButton = new JButton();
        loginButton.setText("Login");
        LoginPanel.add(loginButton, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, new Dimension(150, 20), new Dimension(150, 20), new Dimension(150, 20), 0, false));
        emailField = new JTextField();
        LoginPanel.add(emailField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(250, 20), new Dimension(250, 20), new Dimension(250, 20), 0, false));
        passwordField = new JPasswordField();
        LoginPanel.add(passwordField, new GridConstraints(1, 1, 1, 2, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(250, 20), new Dimension(250, 20), new Dimension(250, 20), 0, false));
        uniRostockDeLabel = new JLabel();
        uniRostockDeLabel.setText("@uni-rostock.de");
        uniRostockDeLabel.setVerticalAlignment(1);
        uniRostockDeLabel.setVerticalTextPosition(1);
        LoginPanel.add(uniRostockDeLabel, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return LoginPanel;
    }
}
