package GUI;

import Controller.MainController;
import Database.DBrequest;
import Database.DatabaseException;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import utilities.SendEmail;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class resetpassword implements FrameContent {
    private JPanel resetpasswordPanel;
    private JTextField emailfield;
    private JLabel emaillabel;
    private JButton zurueckButton;
    private JButton bestaetigenButton;
    private JLabel errorlabel;
    private GUIMain mainFrame;

    public resetpassword() {

        errorlabel.setVisible(false);
        bestaetigenButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String email = emailfield.getText() + "@uni-rostock.de";
                try {
                    if (DBrequest.getIntstance().isInDatabase(email)) {
                        String newpw = mainFrame.getController().generateVerifyingCode();
                        char[] hashChar = MainController.getHash(newpw.toCharArray());
                        String hashString = "";
                        for (int i = 0; i < hashChar.length; i++)
                            hashString = hashString + hashChar[i];
                        SendEmail.send(email, "Neues Passwort", newpw);
                        DBrequest.getIntstance().updateNutzerPasswort(email, hashString);
                        errorlabel.setText("Es wurde ein neues Passwort generiert und an die angegebene Adresse versandt");
                        errorlabel.setVisible(true);
                    } else {
                        errorlabel.setText("E-Mailadresse nicht vorhanden");
                        errorlabel.setVisible(true);
                    }
                } catch (DatabaseException dbe) {
                    System.out.println(dbe.getErrorMsg());
                }
            }
        });
        zurueckButton.addActionListener(e -> mainFrame.setContent(new LoginSeite()));
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        resetpasswordPanel = new JPanel();
        resetpasswordPanel.setLayout(new GridLayoutManager(4, 3, new Insets(150, 150, 450, 300), -1, -1));
        emaillabel = new JLabel();
        emaillabel.setText("E-Mailadresse:");
        resetpasswordPanel.add(emaillabel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        resetpasswordPanel.add(spacer1, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        emailfield = new JTextField();
        emailfield.setText("");
        resetpasswordPanel.add(emailfield, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(250, -1), new Dimension(250, -1), new Dimension(250, -1), 0, false));
        zurueckButton = new JButton();
        zurueckButton.setText("zurück");
        resetpasswordPanel.add(zurueckButton, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        bestaetigenButton = new JButton();
        bestaetigenButton.setText("bestätigen");
        resetpasswordPanel.add(bestaetigenButton, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        errorlabel = new JLabel();
        errorlabel.setText("Es wurde ein neues Passwort generiert und an die angegebene Adresse versandt");
        resetpasswordPanel.add(errorlabel, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("@uni-rostock.de");
        resetpasswordPanel.add(label1, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return resetpasswordPanel;
    }

    @Override
    public String getName() {
        return "resetPassword";
    }

    @Override
    public JPanel getPanel() {
        return resetpasswordPanel;
    }

    @Override
    public void setParentFrame(GUIMain m) {
        mainFrame = m;
    }
}
